### ISSUE TITLE
Wrong readmore link from getReadAll() when no query string

### ISSUE THREAD

**Issue by ReLater** [hoochicken/plg_content_qlwiki#6]
# Plugin settings
![grafik](https://user-images.githubusercontent.com/20780646/229303397-0d417d98-52ae-4cb6-9208-ca32699bc7a5.png)

# Tag in Article
`{qlwiki url="https://de.wikipedia.org/wiki/Joomla"}`

# Result
The readmore `href` is empty instead of `https://de.wikipedia.org/wiki/Joomla`.

# Reason
`$url = substr($this->states['url'], 0, strpos($this->states['url'], '?'));`

returns an empty string because `strpos($this->states['url'], '?')` returns `false` when there is no `?` in url.

# Temporary solution in method `getReadAll()`

```
// get basic url without parameters
if (($strpos = strpos($this->states['url'], '?')) === false)
{
	$strpos = strlen($this->states['url']);
}
$url = substr($this->states['url'], 0, $strpos);
```

**Comment by hoochicken** [comment]
Check for Release https://github.com/hoochicken/plg_content_qlwiki/releases/tag/v1.10.2
Changed some stuff, hope I dodn't add more bugs :-)
